# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

User.create!([
  { :email => "pinak_1180@yahoo.com", :password => "12345678",:password_confirmation=>"12345678" },
  { :email => "jgallardo720@gmail.com",:password => "12345678",:password_confirmation=>"12345678"}
])


