# encoding: utf-8
# Autogenerated by the db:seed:dump task
# Do not hesitate to tweak this to your needs

User.create!([
  { :email => "pinak_1180@yahoo.com", :encrypted_password => "$2a$10$.x.YESY99LmNO/K6Z1tmpODFUf9U.GsxX9uHG7.sR7Cd8lTGYJsDS", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 1, :current_sign_in_at => "2013-11-25 14:51:02", :last_sign_in_at => "2013-11-25 14:51:02", :current_sign_in_ip => "127.0.0.1", :last_sign_in_ip => "127.0.0.1", :created_at => "2013-11-25 14:50:15", :updated_at => "2013-11-25 14:51:02" },
  { :email => "jgallardo720@gmail.com", :encrypted_password => "$2a$10$cR21yEhODWLWr2mY8tNxwOZ3Tz6448oCeeB.fatr04TOQDHBdxK/y", :reset_password_token => nil, :reset_password_sent_at => nil, :remember_created_at => nil, :sign_in_count => 0, :current_sign_in_at => nil, :last_sign_in_at => nil, :current_sign_in_ip => nil, :last_sign_in_ip => nil, :created_at => "2013-11-25 17:55:35", :updated_at => "2013-11-25 17:55:35" }
])


